import type { Riesgo, Configuracion } from './types'

export const mockConfiguracion: Configuracion = {
  id: 1,
  nombre: "Clínica Santa María S.A.S",
  codigo: "MR-CSM-001",
  version: "2.0",
  fecha: "2024-01-15",
  defecto_deficiencia: 2,
  defecto_exposicion: 3,
  defecto_consecuencia: 25
}

export const mockRiesgos: Riesgo[] = [
  {
    id: 1,
    area: "Departamento de Urgencias",
    proceso: "Atención al Paciente",
    responsable: "Dr. Juan Pérez",
    individuo: "Enfermero/a de turno",
    tipo_proceso: "ASISTENCIAL",
    zona: "Urgencias",
    actividad: "Triage y evaluación inicial",
    tarea: "Evaluación de signos vitales y clasificación de pacientes según gravedad",
    cargo: "Enfermero/a Jefe",
    rutinario: true,
    clasificacion: "Biológico",
    peligro_desc: "Exposición a fluidos corporales y agentes patógenos durante la evaluación inicial de pacientes con enfermedades infecciosas no diagnosticadas. Riesgo de contagio por contacto directo con sangre, secreciones respiratorias y otros fluidos.",
    efectos: "Infecciones bacterianas, virales o fúngicas. Posible desarrollo de enfermedades ocupacionales como hepatitis B, hepatitis C, tuberculosis o COVID-19. Impacto en la salud física y mental del personal.",
    deficiencia: 6,
    exposicion: 4,
    consecuencia: 25,
    controles: "Uso obligatorio de EPP (guantes, mascarilla N95, bata, gafas de protección). Lavado de manos según protocolo OMS. Vacunación completa del personal. Capacitación periódica en bioseguridad.",
    intervencion: "Implementar sistema de ventilación mejorado en área de triage. Adquirir dispensadores automáticos de gel antibacterial. Realizar auditorías mensuales de cumplimiento de protocolos.",
    fecha: "2024-02-01",
    seguimiento: "Auditoría mensual de cumplimiento de protocolos de bioseguridad. Registro de incidentes. Evaluación de efectividad de controles implementados."
  },
  {
    id: 2,
    area: "Centro Quirúrgico",
    proceso: "Cirugía",
    responsable: "Dra. María López",
    individuo: "Jefe de quirófano",
    tipo_proceso: "ASISTENCIAL",
    zona: "Quirófano Principal",
    actividad: "Procedimientos quirúrgicos mayores",
    tarea: "Asistencia en cirugías de alta complejidad incluyendo manejo de instrumental cortopunzante",
    cargo: "Instrumentador Quirúrgico",
    rutinario: true,
    clasificacion: "Mecánico",
    peligro_desc: "Manipulación constante de instrumental cortopunzante (bisturís, agujas, tijeras quirúrgicas) en condiciones de alta presión y concentración. Riesgo de cortes y pinchazos accidentales durante procedimientos prolongados.",
    efectos: "Heridas cortantes o punzantes. Riesgo de infección secundaria por contacto con fluidos del paciente. Estrés laboral por alta responsabilidad y consecuencias de errores potenciales.",
    deficiencia: 2,
    exposicion: 4,
    consecuencia: 60,
    controles: "Protocolo de conteo de instrumental pre y post cirugía. Uso de contenedores de bioseguridad para desecho de cortopunzantes. Técnica de no recapsular agujas. Doble guante en procedimientos de alto riesgo.",
    intervencion: "Adquisición de instrumental con sistemas de seguridad integrados. Capacitación en técnicas de manipulación segura. Evaluación ergonómica del espacio de trabajo.",
    fecha: "2024-01-20",
    seguimiento: "Registro de incidentes cortopunzantes. Evaluación trimestral de técnicas de manipulación. Seguimiento a personal expuesto."
  },
  {
    id: 3,
    area: "Servicios Generales",
    proceso: "Limpieza y Desinfección",
    responsable: "Supervisor de Servicios",
    individuo: "Coordinador de área",
    tipo_proceso: "OPERATIVO",
    zona: "Áreas Comunes",
    actividad: "Limpieza y desinfección hospitalaria",
    tarea: "Limpieza de superficies, pisos y baños con productos químicos de desinfección hospitalaria",
    cargo: "Auxiliar de Servicios Generales",
    rutinario: true,
    clasificacion: "Químico",
    peligro_desc: "Exposición prolongada a productos químicos de desinfección (hipoclorito de sodio, glutaraldehído, formaldehído). Manipulación de sustancias concentradas sin adecuada ventilación en algunos espacios.",
    efectos: "Irritación de vías respiratorias y piel. Dermatitis de contacto. Posibles efectos a largo plazo en sistema respiratorio. Sensibilización a químicos con desarrollo de alergias ocupacionales.",
    deficiencia: 6,
    exposicion: 3,
    consecuencia: 25,
    controles: "Fichas de seguridad disponibles. EPP específico para manejo de químicos (guantes de nitrilo, mascarilla con filtro, gafas). Rotación de personal en áreas de mayor exposición.",
    intervencion: "Instalar extractores de aire en áreas cerradas. Sustituir productos de mayor toxicidad por alternativas más seguras. Realizar exámenes médicos ocupacionales semestrales.",
    fecha: "2024-02-10",
    seguimiento: "Monitoreo de calidad del aire. Evaluación dermatológica periódica del personal. Registro de uso de EPP."
  },
  {
    id: 4,
    area: "Hospitalización",
    proceso: "Cuidado de Pacientes",
    responsable: "Enfermero/a Jefe de Piso",
    individuo: "Auxiliar de Enfermería",
    tipo_proceso: "ASISTENCIAL",
    zona: "Pisos de Hospitalización",
    actividad: "Movilización de pacientes",
    tarea: "Traslado y posicionamiento de pacientes con movilidad reducida o nula",
    cargo: "Auxiliar de Enfermería",
    rutinario: true,
    clasificacion: "Ergonómico",
    peligro_desc: "Levantamiento y movilización manual de pacientes con sobrepeso o condiciones especiales. Posturas forzadas durante cambios de posición en cama. Movimientos repetitivos durante turnos prolongados.",
    efectos: "Lesiones musculoesqueléticas en espalda baja, hombros y rodillas. Desarrollo de patologías crónicas como hernias discales, síndrome del túnel carpiano. Fatiga física acumulativa.",
    deficiencia: 6,
    exposicion: 4,
    consecuencia: 25,
    controles: "Capacitación en técnicas de movilización de pacientes. Uso de ayudas mecánicas cuando están disponibles. Pausas activas programadas. Trabajo en equipo para pacientes de difícil movilización.",
    intervencion: "Adquirir grúas para movilización de pacientes. Implementar programa de gimnasia laboral. Diseñar protocolo de movilización segura con evaluación previa del paciente.",
    fecha: "2024-01-25",
    seguimiento: "Evaluación osteomuscular anual. Registro de ausentismo por causas musculoesqueléticas. Seguimiento a casos con restricciones médicas."
  },
  {
    id: 5,
    area: "Laboratorio Clínico",
    proceso: "Análisis de Muestras",
    responsable: "Jefe de Laboratorio",
    individuo: "Técnico de procesamiento",
    tipo_proceso: "ASISTENCIAL",
    zona: "Área de Procesamiento",
    actividad: "Análisis de muestras biológicas",
    tarea: "Procesamiento y análisis de muestras de sangre, orina y otros fluidos corporales",
    cargo: "Bacteriólogo",
    rutinario: true,
    clasificacion: "Biológico",
    peligro_desc: "Manipulación de muestras potencialmente infectadas con diversos patógenos. Riesgo de salpicaduras durante centrifugación y pipeteo. Exposición a aerosoles durante apertura de contenedores.",
    efectos: "Infecciones por contacto con muestras contaminadas. Enfermedades transmitidas por sangre (VIH, Hepatitis). Infecciones respiratorias por aerosoles de muestras con patógenos.",
    deficiencia: 2,
    exposicion: 4,
    consecuencia: 60,
    controles: "Cabinas de bioseguridad clase II para procesamiento. Protocolos estrictos de manejo de muestras. EPP completo obligatorio. Sistema de etiquetado y trazabilidad de muestras.",
    intervencion: "Actualizar cabinas de bioseguridad. Implementar sistema automatizado de pipeteo. Reforzar señalización de áreas de riesgo biológico.",
    fecha: "2024-02-05",
    seguimiento: "Certificación anual de cabinas de bioseguridad. Auditorías de cumplimiento de protocolos. Vigilancia epidemiológica del personal."
  },
  {
    id: 6,
    area: "Radiología",
    proceso: "Diagnóstico por Imagen",
    responsable: "Radiólogo Jefe",
    individuo: "Operador de equipos",
    tipo_proceso: "ASISTENCIAL",
    zona: "Sala de Rayos X",
    actividad: "Toma de imágenes diagnósticas",
    tarea: "Operación de equipos de rayos X y posicionamiento de pacientes para estudios radiológicos",
    cargo: "Tecnólogo en Radiología",
    rutinario: true,
    clasificacion: "Físico",
    peligro_desc: "Exposición a radiación ionizante durante la operación de equipos de rayos X. Riesgo acumulativo por exposición repetida. Posible falla en sistemas de protección radiológica.",
    efectos: "Efectos determinísticos por sobreexposición (quemaduras, cataratas). Efectos estocásticos a largo plazo (incremento en riesgo de cáncer). Alteraciones hematológicas por exposición crónica.",
    deficiencia: 2,
    exposicion: 3,
    consecuencia: 60,
    controles: "Dosimetría personal mensual. Blindaje plomado en sala y EPP (delantales, protectores de tiroides). Distancia de seguridad establecida. Mantenimiento preventivo de equipos.",
    intervencion: "Actualizar sistema de monitoreo de radiación en tiempo real. Renovar equipos de protección personal. Realizar calibración trimestral de equipos emisores.",
    fecha: "2024-01-18",
    seguimiento: "Lectura mensual de dosímetros. Exámenes médicos semestrales específicos. Control de dosis acumulada anual."
  },
  {
    id: 7,
    area: "Farmacia",
    proceso: "Preparación de Medicamentos",
    responsable: "Químico Farmacéutico Jefe",
    individuo: "Asistente de farmacia",
    tipo_proceso: "ASISTENCIAL",
    zona: "Área de Preparación",
    actividad: "Preparación de medicamentos",
    tarea: "Preparación de mezclas intravenosas y medicamentos citotóxicos",
    cargo: "Químico Farmacéutico",
    rutinario: true,
    clasificacion: "Químico",
    peligro_desc: "Manipulación de medicamentos citotóxicos y preparaciones estériles. Exposición a partículas de medicamentos durante preparación. Riesgo de contaminación cruzada y exposición dérmica.",
    efectos: "Efectos mutagénicos y carcinogénicos por exposición a citotóxicos. Reacciones alérgicas a medicamentos. Contaminación de preparaciones con riesgo para pacientes.",
    deficiencia: 2,
    exposicion: 3,
    consecuencia: 100,
    controles: "Cabina de flujo laminar para preparaciones estériles. Cabina de seguridad biológica para citotóxicos. EPP especializado (doble guante de quimioterapia, bata impermeable, mascarilla N95).",
    intervencion: "Implementar sistema cerrado de transferencia de medicamentos. Capacitación especializada en manejo de citotóxicos. Monitoreo ambiental de contaminación.",
    fecha: "2024-02-12",
    seguimiento: "Evaluación médica trimestral. Monitoreo de superficies para detectar contaminación. Auditoría de técnica aséptica."
  },
  {
    id: 8,
    area: "Mantenimiento",
    responsable: "Supervisor de Mantenimiento",
    proceso: "Mantenimiento",
    individuo: "Técnico de mantenimiento",
    tipo_proceso: "OPERATIVO",
    zona: "Cuarto de Máquinas",
    actividad: "Mantenimiento de equipos eléctricos",
    tarea: "Revisión y reparación de sistemas eléctricos de media y baja tensión",
    cargo: "Técnico Electricista",
    rutinario: false,
    clasificacion: "Eléctrico",
    peligro_desc: "Trabajo con sistemas eléctricos energizados. Riesgo de contacto directo e indirecto con corriente eléctrica. Posibilidad de arco eléctrico durante intervenciones.",
    efectos: "Electrocución con consecuencias fatales. Quemaduras eléctricas graves. Fibrilación ventricular. Caídas por impacto eléctrico.",
    deficiencia: 6,
    exposicion: 2,
    consecuencia: 100,
    controles: "Procedimiento de bloqueo y etiquetado (LOTO). EPP dieléctrico certificado. Detector de tensión antes de intervención. Trabajo siempre en parejas.",
    intervencion: "Actualizar procedimientos según norma NFPA 70E. Adquirir herramientas dieléctricas certificadas. Instalar señalización de riesgo eléctrico en todos los tableros.",
    fecha: "2024-01-30",
    seguimiento: "Verificación mensual de estado de EPP dieléctrico. Auditoría de cumplimiento de procedimiento LOTO. Capacitación anual en riesgo eléctrico."
  }
]
